services:
  container1:
    image: archlinux
    privileged: true
    command: sleep infinity
    volumes:
       - ./wag:/usr/local/bin/wag
    networks:
      custom_network:
        ipv4_address: 172.20.0.2
    cap_add:
      - NET_ADMIN

  container2:
    image: archlinux
    privileged: true
    command: sleep infinity
    ports:
      - "4433:4433/tcp"
      - "53230:53230/udp"
      - "8081:8081/tcp"
    volumes:
       - .:/usr/local/bin/wag:ro
       - ./docker-test-config.json:/opt/config.json
       - ./devices.db:/opt/devices.db
    networks:
      custom_network:
        ipv4_address: 172.20.0.3
    cap_add:
      - NET_ADMIN

  container3:
    image: archlinux
    privileged: true
    volumes:
       - ./wag:/usr/local/bin/wag
    command: sleep infinity
    networks:
      custom_network:
        ipv4_address: 172.20.0.4
    cap_add:
      - NET_ADMIN

  speedtest:
     image: mlabbe/iperf3
     networks:
      custom_network:
        ipv4_address: 172.20.0.5

networks:
  custom_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1