// Code generated by https://github.com/NHAS/tetcd, DO NOT EDIT.
package data

import (
	"context"
	tetcd "github.com/NHAS/tetcd"
	codecs "github.com/NHAS/tetcd/codecs"
	paths "github.com/NHAS/tetcd/paths"
	tree "github.com/NHAS/tetcd/tree"
	watch "github.com/NHAS/tetcd/watch"
	specialist "github.com/NHAS/tetcd/watch/specialist"
	config "github.com/NHAS/wag/internal/config"
	control "github.com/NHAS/wag/pkg/control"
	v3 "go.etcd.io/etcd/client/v3"
	"time"
)

type autoTypeDevicesDHCP struct{}

// Abandoned() is a map path with prefix wag-config-internal/InternalConfig/Devices/DHCP/Abandoned, value type string
func (autoTypeDevicesDHCP) Abandoned() paths.MapPath[string] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Devices/DHCP/Abandoned", codecs.NewJsonCodec[string](), false)
}

// End() KV should contain type string
func (autoTypeDevicesDHCP) End() paths.Path[string] {
	return paths.NewPath("wag-config-internal/InternalConfig/Devices/DHCP/End", codecs.NewJsonCodec[string]())
}

// Locks() KV should contain type string
func (autoTypeDevicesDHCP) Locks() paths.Path[string] {
	return paths.NewPath("wag-config-internal/InternalConfig/Devices/DHCP/Locks", codecs.NewJsonCodec[string]())
}

// Get fetches all fields of DHCP in one or more transactions pinned to the same etcd revision.
func (a autoTypeDevicesDHCP) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result config.DHCP, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.ListTx(txn0.Then(), a.Abandoned())
	h0_1 := tetcd.GetTx(txn0.Then(), a.End())
	h0_2 := tetcd.GetTx(txn0.Then(), a.Locks())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Abandoned, err = h0_0.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.End, err = h0_1.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.Locks, err = h0_2.Value()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeDevicesDHCP) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result config.DHCP, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full DHCP struct whenever any sub-key changes.
func (a autoTypeDevicesDHCP) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[config.DHCP] {
	return specialist.NewAllWatcher(ctx, cli, "wag-config-internal/InternalConfig/Devices/DHCP/", a.GetWithFail)
}

type autoTypeInternalConfigDevices struct {
	DHCP autoTypeDevicesDHCP
}

// Challenges() is a slice map path with prefix wag-config-internal/InternalConfig/Devices/Challenges, value type github.com/NHAS/wag/internal/config.DeviceChallenge
func (autoTypeInternalConfigDevices) Challenges() paths.MapSlicePath[config.DeviceChallenge] {
	return paths.NewMapSlicePath("wag-config-internal/InternalConfig/Devices/Challenges", codecs.NewJsonCodec[config.DeviceChallenge](), false)
}

// Machines() is a slice map path with prefix wag-config-internal/InternalConfig/Devices/Machines, value type github.com/NHAS/wag/internal/config.Device
func (autoTypeInternalConfigDevices) Machines() paths.MapSlicePath[config.Device] {
	return paths.NewMapSlicePath("wag-config-internal/InternalConfig/Devices/Machines", codecs.NewJsonCodec[config.Device](), false)
}

// Sessions() is a map path with prefix wag-config-internal/InternalConfig/Devices/Sessions, value type github.com/NHAS/wag/internal/config.DeviceSession
func (autoTypeInternalConfigDevices) Sessions() paths.MapPath[config.DeviceSession] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Devices/Sessions", codecs.NewJsonCodec[config.DeviceSession](), false)
}

// Get fetches all fields of Devices in one or more transactions pinned to the same etcd revision.
func (a autoTypeInternalConfigDevices) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result config.Devices, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.DynamicCollectionTx(txn0.Then(), a.Challenges())
	h0_1 := tetcd.ListTx(txn0.Then(), a.DHCP.Abandoned())
	h0_2 := tetcd.GetTx(txn0.Then(), a.DHCP.End())
	h0_3 := tetcd.GetTx(txn0.Then(), a.DHCP.Locks())
	h0_4 := tetcd.DynamicCollectionTx(txn0.Then(), a.Machines())
	h0_5 := tetcd.ListTx(txn0.Then(), a.Sessions())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Challenges, err = h0_0.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.DHCP.Abandoned, err = h0_1.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.DHCP.End, err = h0_2.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.DHCP.Locks, err = h0_3.Value()
	if err != nil && failEarly {
		return result, err
	}
	result.Machines, err = h0_4.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.Sessions, err = h0_5.Entries()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeInternalConfigDevices) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result config.Devices, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full Devices struct whenever any sub-key changes.
func (a autoTypeInternalConfigDevices) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[config.Devices] {
	return specialist.NewAllWatcher(ctx, cli, "wag-config-internal/InternalConfig/Devices/", a.GetWithFail)
}

type autoTypeInternalConfigIndexes struct{}

// Groups() is a map path with prefix wag-config-internal/InternalConfig/Indexes/Groups, value type github.com/NHAS/wag/internal/config.GroupInfo
func (autoTypeInternalConfigIndexes) Groups() paths.MapPath[config.GroupInfo] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Indexes/Groups", codecs.NewJsonCodec[config.GroupInfo](), false)
}

// UserMembership() is a slice map path with prefix wag-config-internal/InternalConfig/Indexes/UserMembership, value type github.com/NHAS/wag/internal/config.MembershipInfo
func (autoTypeInternalConfigIndexes) UserMembership() paths.MapSlicePath[config.MembershipInfo] {
	return paths.NewMapSlicePath("wag-config-internal/InternalConfig/Indexes/UserMembership", codecs.NewJsonCodec[config.MembershipInfo](), false)
}

// Get fetches all fields of Indexes in one or more transactions pinned to the same etcd revision.
func (a autoTypeInternalConfigIndexes) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result config.Indexes, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.ListTx(txn0.Then(), a.Groups())
	h0_1 := tetcd.DynamicCollectionTx(txn0.Then(), a.UserMembership())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Groups, err = h0_0.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.UserMembership, err = h0_1.Entries()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeInternalConfigIndexes) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result config.Indexes, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full Indexes struct whenever any sub-key changes.
func (a autoTypeInternalConfigIndexes) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[config.Indexes] {
	return specialist.NewAllWatcher(ctx, cli, "wag-config-internal/InternalConfig/Indexes/", a.GetWithFail)
}

type autoTypeInternalConfigNodes struct{}

// Errors() is a map path with prefix wag-config-internal/InternalConfig/Nodes/Errors, value type github.com/NHAS/wag/internal/config.EventError
func (autoTypeInternalConfigNodes) Errors() paths.MapPath[config.EventError] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Nodes/Errors", codecs.NewJsonCodec[config.EventError](), false)
}

// Version() is a map path with prefix wag-config-internal/InternalConfig/Nodes/Version, value type string
func (autoTypeInternalConfigNodes) Version() paths.MapPath[string] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Nodes/Version", codecs.NewJsonCodec[string](), false)
}

// Get fetches all fields of Nodes in one or more transactions pinned to the same etcd revision.
func (a autoTypeInternalConfigNodes) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result config.Nodes, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.ListTx(txn0.Then(), a.Errors())
	h0_1 := tetcd.ListTx(txn0.Then(), a.Version())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Errors, err = h0_0.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.Version, err = h0_1.Entries()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeInternalConfigNodes) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result config.Nodes, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full Nodes struct whenever any sub-key changes.
func (a autoTypeInternalConfigNodes) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[config.Nodes] {
	return specialist.NewAllWatcher(ctx, cli, "wag-config-internal/InternalConfig/Nodes/", a.GetWithFail)
}

type autoTypeReferencesAdmins struct{}

// OidcGuid() is a map path with prefix wag-config-internal/InternalConfig/References/Admins/OidcGuid, value type string
func (autoTypeReferencesAdmins) OidcGuid() paths.MapPath[string] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/References/Admins/OidcGuid", codecs.NewJsonCodec[string](), false)
}

// Get fetches all fields of AdminsReferences in one or more transactions pinned to the same etcd revision.
func (a autoTypeReferencesAdmins) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result config.AdminsReferences, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.ListTx(txn0.Then(), a.OidcGuid())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.OidcGuid, err = h0_0.Entries()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeReferencesAdmins) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result config.AdminsReferences, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full AdminsReferences struct whenever any sub-key changes.
func (a autoTypeReferencesAdmins) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[config.AdminsReferences] {
	return specialist.NewAllWatcher(ctx, cli, "wag-config-internal/InternalConfig/References/Admins/", a.GetWithFail)
}

type autoTypeReferencesDevices struct{}

// Address() is a map path with prefix wag-config-internal/InternalConfig/References/Devices/Address, value type github.com/NHAS/wag/internal/config.DeviceRef
func (autoTypeReferencesDevices) Address() paths.MapPath[config.DeviceRef] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/References/Devices/Address", codecs.NewJsonCodec[config.DeviceRef](), false)
}

// PublicKey() is a map path with prefix wag-config-internal/InternalConfig/References/Devices/PublicKey, value type github.com/NHAS/wag/internal/config.DeviceRef
func (autoTypeReferencesDevices) PublicKey() paths.MapPath[config.DeviceRef] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/References/Devices/PublicKey", codecs.NewJsonCodec[config.DeviceRef](), false)
}

// Tag() is a map path with prefix wag-config-internal/InternalConfig/References/Devices/Tag, value type github.com/NHAS/wag/internal/config.DeviceRef
func (autoTypeReferencesDevices) Tag() paths.MapPath[config.DeviceRef] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/References/Devices/Tag", codecs.NewJsonCodec[config.DeviceRef](), false)
}

// Get fetches all fields of DevicesReferences in one or more transactions pinned to the same etcd revision.
func (a autoTypeReferencesDevices) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result config.DevicesReferences, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.ListTx(txn0.Then(), a.Address())
	h0_1 := tetcd.ListTx(txn0.Then(), a.PublicKey())
	h0_2 := tetcd.ListTx(txn0.Then(), a.Tag())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Address, err = h0_0.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.PublicKey, err = h0_1.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.Tag, err = h0_2.Entries()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeReferencesDevices) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result config.DevicesReferences, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full DevicesReferences struct whenever any sub-key changes.
func (a autoTypeReferencesDevices) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[config.DevicesReferences] {
	return specialist.NewAllWatcher(ctx, cli, "wag-config-internal/InternalConfig/References/Devices/", a.GetWithFail)
}

type autoTypeInternalConfigReferences struct {
	Admins  autoTypeReferencesAdmins
	Devices autoTypeReferencesDevices
}

// Get fetches all fields of References in one or more transactions pinned to the same etcd revision.
func (a autoTypeInternalConfigReferences) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result config.References, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.ListTx(txn0.Then(), a.Admins.OidcGuid())
	h0_1 := tetcd.ListTx(txn0.Then(), a.Devices.Address())
	h0_2 := tetcd.ListTx(txn0.Then(), a.Devices.PublicKey())
	h0_3 := tetcd.ListTx(txn0.Then(), a.Devices.Tag())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Admins.OidcGuid, err = h0_0.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.Devices.Address, err = h0_1.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.Devices.PublicKey, err = h0_2.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.Devices.Tag, err = h0_3.Entries()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeInternalConfigReferences) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result config.References, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full References struct whenever any sub-key changes.
func (a autoTypeInternalConfigReferences) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[config.References] {
	return specialist.NewAllWatcher(ctx, cli, "wag-config-internal/InternalConfig/References/", a.GetWithFail)
}

type autoTypeWebhooksLastRequests struct{}

// Data() is a map path with prefix wag-config-internal/InternalConfig/Webhooks/LastRequests/Data, value type string
func (autoTypeWebhooksLastRequests) Data() paths.MapPath[string] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Webhooks/LastRequests/Data", codecs.NewJsonCodec[string](), false)
}

// Status() is a map path with prefix wag-config-internal/InternalConfig/Webhooks/LastRequests/Status, value type string
func (autoTypeWebhooksLastRequests) Status() paths.MapPath[string] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Webhooks/LastRequests/Status", codecs.NewJsonCodec[string](), false)
}

// Time() is a map path with prefix wag-config-internal/InternalConfig/Webhooks/LastRequests/Time, value type time.Time
func (autoTypeWebhooksLastRequests) Time() paths.MapPath[time.Time] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Webhooks/LastRequests/Time", codecs.NewJsonCodec[time.Time](), false)
}

// Get fetches all fields of LastRequests in one or more transactions pinned to the same etcd revision.
func (a autoTypeWebhooksLastRequests) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result config.LastRequests, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.ListTx(txn0.Then(), a.Data())
	h0_1 := tetcd.ListTx(txn0.Then(), a.Status())
	h0_2 := tetcd.ListTx(txn0.Then(), a.Time())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Data, err = h0_0.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.Status, err = h0_1.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.Time, err = h0_2.Entries()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeWebhooksLastRequests) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result config.LastRequests, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full LastRequests struct whenever any sub-key changes.
func (a autoTypeWebhooksLastRequests) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[config.LastRequests] {
	return specialist.NewAllWatcher(ctx, cli, "wag-config-internal/InternalConfig/Webhooks/LastRequests/", a.GetWithFail)
}

type autoTypeInternalConfigWebhooks struct {
	LastRequests autoTypeWebhooksLastRequests
}

// Active() is a map path with prefix wag-config-internal/InternalConfig/Webhooks/Active, value type github.com/NHAS/wag/internal/config.Webhook
func (autoTypeInternalConfigWebhooks) Active() paths.MapPath[config.Webhook] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Webhooks/Active", codecs.NewJsonCodec[config.Webhook](), false)
}

// Auth() is a map path with prefix wag-config-internal/InternalConfig/Webhooks/Auth, value type string
func (autoTypeInternalConfigWebhooks) Auth() paths.MapPath[string] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Webhooks/Auth", codecs.NewJsonCodec[string](), false)
}

// Temporary() is a map path with prefix wag-config-internal/InternalConfig/Webhooks/Temporary, value type github.com/NHAS/wag/internal/config.Webhook
func (autoTypeInternalConfigWebhooks) Temporary() paths.MapPath[config.Webhook] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Webhooks/Temporary", codecs.NewJsonCodec[config.Webhook](), false)
}

// Get fetches all fields of Webhooks in one or more transactions pinned to the same etcd revision.
func (a autoTypeInternalConfigWebhooks) GetWithFail(ctx context.Context, cli *v3.Client, failEarly bool, opts ...tetcd.TxnOp) (result config.Webhooks, err error) {
	txn0 := tetcd.NewTxn(ctx, cli, opts...)
	h0_0 := tetcd.ListTx(txn0.Then(), a.Active())
	h0_1 := tetcd.ListTx(txn0.Then(), a.Auth())
	h0_2 := tetcd.ListTx(txn0.Then(), a.LastRequests.Data())
	h0_3 := tetcd.ListTx(txn0.Then(), a.LastRequests.Status())
	h0_4 := tetcd.ListTx(txn0.Then(), a.LastRequests.Time())
	h0_5 := tetcd.ListTx(txn0.Then(), a.Temporary())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Active, err = h0_0.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.Auth, err = h0_1.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.LastRequests.Data, err = h0_2.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.LastRequests.Status, err = h0_3.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.LastRequests.Time, err = h0_4.Entries()
	if err != nil && failEarly {
		return result, err
	}
	result.Temporary, err = h0_5.Entries()
	if err != nil && failEarly {
		return result, err
	}
	return result, nil
}
func (a autoTypeInternalConfigWebhooks) Get(ctx context.Context, cli *v3.Client, opts ...tetcd.TxnOp) (result config.Webhooks, err error) {
	return a.GetWithFail(ctx, cli, false, opts...)
}

// Watch returns a Watcher that emits the full Webhooks struct whenever any sub-key changes.
func (a autoTypeInternalConfigWebhooks) Watch(ctx context.Context, cli *v3.Client) *watch.Watcher[config.Webhooks] {
	return specialist.NewAllWatcher(ctx, cli, "wag-config-internal/InternalConfig/Webhooks/", a.GetWithFail)
}

type autoTypeInternalConfig struct {
	Devices    autoTypeInternalConfigDevices
	Indexes    autoTypeInternalConfigIndexes
	Nodes      autoTypeInternalConfigNodes
	References autoTypeInternalConfigReferences
	Webhooks   autoTypeInternalConfigWebhooks
}

// Admins() is a map path with prefix wag-config-internal/InternalConfig/Admins, value type github.com/NHAS/wag/internal/config.Admin
func (autoTypeInternalConfig) Admins() paths.MapPath[config.Admin] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Admins", codecs.NewJsonCodec[config.Admin](), false)
}

// RegistrationTokens() is a map path with prefix wag-config-internal/InternalConfig/RegistrationTokens, value type github.com/NHAS/wag/pkg/control.RegistrationResult
func (autoTypeInternalConfig) RegistrationTokens() paths.MapPath[control.RegistrationResult] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/RegistrationTokens", codecs.NewJsonCodec[control.RegistrationResult](), false)
}

// Users() is a map path with prefix wag-config-internal/InternalConfig/Users, value type github.com/NHAS/wag/internal/config.UserModel
func (autoTypeInternalConfig) Users() paths.MapPath[config.UserModel] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Users", codecs.NewJsonCodec[config.UserModel](), false)
}

var (
	InternalConfig       = autoTypeInternalConfig{}
	InternalConfigDiffer = tree.NewTreeWithPrefix[config.InternalConfig]("wag-config-internal")
)

// init() builds the tree structure to automatically apply diffs to etcd
func init() {
	InternalConfigDiffer.Register(InternalConfig.Admins())
	InternalConfigDiffer.Register(InternalConfig.Devices.Challenges())
	InternalConfigDiffer.Register(InternalConfig.Devices.DHCP.Abandoned())
	InternalConfigDiffer.Register(InternalConfig.Devices.DHCP.End())
	InternalConfigDiffer.Register(InternalConfig.Devices.DHCP.Locks())
	InternalConfigDiffer.Register(InternalConfig.Devices.Machines())
	InternalConfigDiffer.Register(InternalConfig.Devices.Sessions())
	InternalConfigDiffer.Register(InternalConfig.Indexes.Groups())
	InternalConfigDiffer.Register(InternalConfig.Indexes.UserMembership())
	InternalConfigDiffer.Register(InternalConfig.Nodes.Errors())
	InternalConfigDiffer.Register(InternalConfig.Nodes.Version())
	InternalConfigDiffer.Register(InternalConfig.References.Admins.OidcGuid())
	InternalConfigDiffer.Register(InternalConfig.References.Devices.Address())
	InternalConfigDiffer.Register(InternalConfig.References.Devices.PublicKey())
	InternalConfigDiffer.Register(InternalConfig.References.Devices.Tag())
	InternalConfigDiffer.Register(InternalConfig.RegistrationTokens())
	InternalConfigDiffer.Register(InternalConfig.Users())
	InternalConfigDiffer.Register(InternalConfig.Webhooks.Active())
	InternalConfigDiffer.Register(InternalConfig.Webhooks.Auth())
	InternalConfigDiffer.Register(InternalConfig.Webhooks.LastRequests.Data())
	InternalConfigDiffer.Register(InternalConfig.Webhooks.LastRequests.Status())
	InternalConfigDiffer.Register(InternalConfig.Webhooks.LastRequests.Time())
	InternalConfigDiffer.Register(InternalConfig.Webhooks.Temporary())
}
