// Code generated by https://github.com/NHAS/tetcd, DO NOT EDIT.
package data

import (
	"context"
	tetcd "github.com/NHAS/tetcd"
	codecs "github.com/NHAS/tetcd/codecs"
	paths "github.com/NHAS/tetcd/paths"
	acls "github.com/NHAS/wag/internal/acls"
	config "github.com/NHAS/wag/internal/config"
	v3 "go.etcd.io/etcd/client/v3"
	"net"
)

type autoTypeConfigAcls struct{}

// Groups() is a slice map path with prefix wag-config/Config/Acls/Groups, value type github.com/NHAS/wag/internal/config.MembershipInfo
func (autoTypeConfigAcls) Groups() paths.MapSlicePath[config.MembershipInfo] {
	return paths.NewMapSlicePath("wag-config/Config/Acls/Groups", codecs.NewJsonCodec[config.MembershipInfo](), false)
}

// Policies() is a map path with prefix wag-config/Config/Acls/Policies, value type *github.com/NHAS/wag/internal/acls.Acl
func (autoTypeConfigAcls) Policies() paths.MapPath[*acls.Acl] {
	return paths.NewMapPath("wag-config/Config/Acls/Policies", codecs.NewJsonCodec[*acls.Acl](), false)
}

// Get fetches all fields of Acls in one or more transactions pinned to the same etcd revision.
func (a autoTypeConfigAcls) Get(ctx context.Context, cli *v3.Client) (result config.Acls, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.DynamicCollectionTx(txn0.Then(), a.Groups())
	h0_1 := tetcd.ListTx(txn0.Then(), a.Policies())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Groups, err = h0_0.Entries()
	if err != nil {
		return result, err
	}
	result.Policies, err = h0_1.Entries()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeWebserverAcme struct{}

// CAProvider() KV should contain type string
func (autoTypeWebserverAcme) CAProvider() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Acme/CAProvider", codecs.NewJsonCodec[string]())
}

// CloudflareDNSToken() KV should contain type string
func (autoTypeWebserverAcme) CloudflareDNSToken() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Acme/CloudflareDNSToken", codecs.NewJsonCodec[string]())
}

// Email() KV should contain type string
func (autoTypeWebserverAcme) Email() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Acme/Email", codecs.NewJsonCodec[string]())
}

type resultWebserverAcme struct {
	Email              string
	CAProvider         string
	CloudflareDNSToken string
}

// Get fetches all fields of resultWebserverAcme in one or more transactions pinned to the same etcd revision.
func (a autoTypeWebserverAcme) Get(ctx context.Context, cli *v3.Client) (result resultWebserverAcme, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.GetTx(txn0.Then(), a.CAProvider())
	h0_1 := tetcd.GetTx(txn0.Then(), a.CloudflareDNSToken())
	h0_2 := tetcd.GetTx(txn0.Then(), a.Email())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.CAProvider, err = h0_0.Value()
	if err != nil {
		return result, err
	}
	result.CloudflareDNSToken, err = h0_1.Value()
	if err != nil {
		return result, err
	}
	result.Email, err = h0_2.Value()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeManagementHTTPSettings struct{}

// CertificatePEM() KV should contain type string
func (autoTypeManagementHTTPSettings) CertificatePEM() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Management/HTTPSettings/CertificatePEM", codecs.NewJsonCodec[string]())
}

// CertificatePath() KV should contain type string
func (autoTypeManagementHTTPSettings) CertificatePath() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Management/HTTPSettings/CertificatePath", codecs.NewJsonCodec[string]())
}

// Domain() KV should contain type string
func (autoTypeManagementHTTPSettings) Domain() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Management/HTTPSettings/Domain", codecs.NewJsonCodec[string]())
}

// ListenAddress() KV should contain type string
func (autoTypeManagementHTTPSettings) ListenAddress() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Management/HTTPSettings/ListenAddress", codecs.NewJsonCodec[string]())
}

// PrivateKeyPEM() KV should contain type string
func (autoTypeManagementHTTPSettings) PrivateKeyPEM() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Management/HTTPSettings/PrivateKeyPEM", codecs.NewJsonCodec[string]())
}

// PrivateKeyPath() KV should contain type string
func (autoTypeManagementHTTPSettings) PrivateKeyPath() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Management/HTTPSettings/PrivateKeyPath", codecs.NewJsonCodec[string]())
}

// StaticCerts() KV should contain type bool
func (autoTypeManagementHTTPSettings) StaticCerts() paths.Path[bool] {
	return paths.NewPath("wag-config/Config/Webserver/Management/HTTPSettings/StaticCerts", codecs.NewJsonCodec[bool]())
}

// TLS() KV should contain type bool
func (autoTypeManagementHTTPSettings) TLS() paths.Path[bool] {
	return paths.NewPath("wag-config/Config/Webserver/Management/HTTPSettings/TLS", codecs.NewJsonCodec[bool]())
}

// Get fetches all fields of WebserverDetails in one or more transactions pinned to the same etcd revision.
func (a autoTypeManagementHTTPSettings) Get(ctx context.Context, cli *v3.Client) (result config.WebserverDetails, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.GetTx(txn0.Then(), a.CertificatePEM())
	h0_1 := tetcd.GetTx(txn0.Then(), a.CertificatePath())
	h0_2 := tetcd.GetTx(txn0.Then(), a.Domain())
	h0_3 := tetcd.GetTx(txn0.Then(), a.ListenAddress())
	h0_4 := tetcd.GetTx(txn0.Then(), a.PrivateKeyPEM())
	h0_5 := tetcd.GetTx(txn0.Then(), a.PrivateKeyPath())
	h0_6 := tetcd.GetTx(txn0.Then(), a.StaticCerts())
	h0_7 := tetcd.GetTx(txn0.Then(), a.TLS())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.CertificatePEM, err = h0_0.Value()
	if err != nil {
		return result, err
	}
	result.CertificatePath, err = h0_1.Value()
	if err != nil {
		return result, err
	}
	result.Domain, err = h0_2.Value()
	if err != nil {
		return result, err
	}
	result.ListenAddress, err = h0_3.Value()
	if err != nil {
		return result, err
	}
	result.PrivateKeyPEM, err = h0_4.Value()
	if err != nil {
		return result, err
	}
	result.PrivateKeyPath, err = h0_5.Value()
	if err != nil {
		return result, err
	}
	result.StaticCerts, err = h0_6.Value()
	if err != nil {
		return result, err
	}
	result.TLS, err = h0_7.Value()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeManagementOIDC struct{}

// ClientID() KV should contain type string
func (autoTypeManagementOIDC) ClientID() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Management/OIDC/ClientID", codecs.NewJsonCodec[string]())
}

// ClientSecret() KV should contain type string
func (autoTypeManagementOIDC) ClientSecret() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Management/OIDC/ClientSecret", codecs.NewJsonCodec[string]())
}

// Enabled() KV should contain type bool
func (autoTypeManagementOIDC) Enabled() paths.Path[bool] {
	return paths.NewPath("wag-config/Config/Webserver/Management/OIDC/Enabled", codecs.NewJsonCodec[bool]())
}

// IssuerURL() KV should contain type string
func (autoTypeManagementOIDC) IssuerURL() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Management/OIDC/IssuerURL", codecs.NewJsonCodec[string]())
}

type resultManagementOIDC struct {
	IssuerURL    string
	ClientSecret string
	ClientID     string
	Enabled      bool
}

// Get fetches all fields of resultManagementOIDC in one or more transactions pinned to the same etcd revision.
func (a autoTypeManagementOIDC) Get(ctx context.Context, cli *v3.Client) (result resultManagementOIDC, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.GetTx(txn0.Then(), a.ClientID())
	h0_1 := tetcd.GetTx(txn0.Then(), a.ClientSecret())
	h0_2 := tetcd.GetTx(txn0.Then(), a.Enabled())
	h0_3 := tetcd.GetTx(txn0.Then(), a.IssuerURL())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.ClientID, err = h0_0.Value()
	if err != nil {
		return result, err
	}
	result.ClientSecret, err = h0_1.Value()
	if err != nil {
		return result, err
	}
	result.Enabled, err = h0_2.Value()
	if err != nil {
		return result, err
	}
	result.IssuerURL, err = h0_3.Value()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeManagementPassword struct{}

// Enabled() KV should contain type *bool
func (autoTypeManagementPassword) Enabled() paths.Path[*bool] {
	return paths.NewPath("wag-config/Config/Webserver/Management/Password/Enabled", codecs.NewJsonCodec[*bool]())
}

type resultManagementPassword struct {
	Enabled *bool
}

// Get fetches all fields of resultManagementPassword in one or more transactions pinned to the same etcd revision.
func (a autoTypeManagementPassword) Get(ctx context.Context, cli *v3.Client) (result resultManagementPassword, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.GetTx(txn0.Then(), a.Enabled())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Enabled, err = h0_0.Value()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeWebserverManagement struct {
	HTTPSettings autoTypeManagementHTTPSettings
	OIDC         autoTypeManagementOIDC
	Password     autoTypeManagementPassword
}

// Enabled() KV should contain type bool
func (autoTypeWebserverManagement) Enabled() paths.Path[bool] {
	return paths.NewPath("wag-config/Config/Webserver/Management/Enabled", codecs.NewJsonCodec[bool]())
}

type resultWebserverManagement struct {
	HTTPSettings config.WebserverDetails
	Enabled      bool
	Password     struct {
		Enabled *bool
	}
	OIDC struct {
		IssuerURL    string
		ClientSecret string
		ClientID     string
		Enabled      bool
	}
}

// Get fetches all fields of resultWebserverManagement in one or more transactions pinned to the same etcd revision.
func (a autoTypeWebserverManagement) Get(ctx context.Context, cli *v3.Client) (result resultWebserverManagement, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.GetTx(txn0.Then(), a.Enabled())
	h0_1 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.CertificatePEM())
	h0_2 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.CertificatePath())
	h0_3 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.Domain())
	h0_4 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.ListenAddress())
	h0_5 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.PrivateKeyPEM())
	h0_6 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.PrivateKeyPath())
	h0_7 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.StaticCerts())
	h0_8 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.TLS())
	h0_9 := tetcd.GetTx(txn0.Then(), a.OIDC.ClientID())
	h0_10 := tetcd.GetTx(txn0.Then(), a.OIDC.ClientSecret())
	h0_11 := tetcd.GetTx(txn0.Then(), a.OIDC.Enabled())
	h0_12 := tetcd.GetTx(txn0.Then(), a.OIDC.IssuerURL())
	h0_13 := tetcd.GetTx(txn0.Then(), a.Password.Enabled())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Enabled, err = h0_0.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.CertificatePEM, err = h0_1.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.CertificatePath, err = h0_2.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.Domain, err = h0_3.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.ListenAddress, err = h0_4.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.PrivateKeyPEM, err = h0_5.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.PrivateKeyPath, err = h0_6.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.StaticCerts, err = h0_7.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.TLS, err = h0_8.Value()
	if err != nil {
		return result, err
	}
	result.OIDC.ClientID, err = h0_9.Value()
	if err != nil {
		return result, err
	}
	result.OIDC.ClientSecret, err = h0_10.Value()
	if err != nil {
		return result, err
	}
	result.OIDC.Enabled, err = h0_11.Value()
	if err != nil {
		return result, err
	}
	result.OIDC.IssuerURL, err = h0_12.Value()
	if err != nil {
		return result, err
	}
	result.Password.Enabled, err = h0_13.Value()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypePublicHTTPSettings struct{}

// CertificatePEM() KV should contain type string
func (autoTypePublicHTTPSettings) CertificatePEM() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Public/HTTPSettings/CertificatePEM", codecs.NewJsonCodec[string]())
}

// CertificatePath() KV should contain type string
func (autoTypePublicHTTPSettings) CertificatePath() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Public/HTTPSettings/CertificatePath", codecs.NewJsonCodec[string]())
}

// Domain() KV should contain type string
func (autoTypePublicHTTPSettings) Domain() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Public/HTTPSettings/Domain", codecs.NewJsonCodec[string]())
}

// ListenAddress() KV should contain type string
func (autoTypePublicHTTPSettings) ListenAddress() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Public/HTTPSettings/ListenAddress", codecs.NewJsonCodec[string]())
}

// PrivateKeyPEM() KV should contain type string
func (autoTypePublicHTTPSettings) PrivateKeyPEM() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Public/HTTPSettings/PrivateKeyPEM", codecs.NewJsonCodec[string]())
}

// PrivateKeyPath() KV should contain type string
func (autoTypePublicHTTPSettings) PrivateKeyPath() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Public/HTTPSettings/PrivateKeyPath", codecs.NewJsonCodec[string]())
}

// StaticCerts() KV should contain type bool
func (autoTypePublicHTTPSettings) StaticCerts() paths.Path[bool] {
	return paths.NewPath("wag-config/Config/Webserver/Public/HTTPSettings/StaticCerts", codecs.NewJsonCodec[bool]())
}

// TLS() KV should contain type bool
func (autoTypePublicHTTPSettings) TLS() paths.Path[bool] {
	return paths.NewPath("wag-config/Config/Webserver/Public/HTTPSettings/TLS", codecs.NewJsonCodec[bool]())
}

// Get fetches all fields of WebserverDetails in one or more transactions pinned to the same etcd revision.
func (a autoTypePublicHTTPSettings) Get(ctx context.Context, cli *v3.Client) (result config.WebserverDetails, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.GetTx(txn0.Then(), a.CertificatePEM())
	h0_1 := tetcd.GetTx(txn0.Then(), a.CertificatePath())
	h0_2 := tetcd.GetTx(txn0.Then(), a.Domain())
	h0_3 := tetcd.GetTx(txn0.Then(), a.ListenAddress())
	h0_4 := tetcd.GetTx(txn0.Then(), a.PrivateKeyPEM())
	h0_5 := tetcd.GetTx(txn0.Then(), a.PrivateKeyPath())
	h0_6 := tetcd.GetTx(txn0.Then(), a.StaticCerts())
	h0_7 := tetcd.GetTx(txn0.Then(), a.TLS())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.CertificatePEM, err = h0_0.Value()
	if err != nil {
		return result, err
	}
	result.CertificatePath, err = h0_1.Value()
	if err != nil {
		return result, err
	}
	result.Domain, err = h0_2.Value()
	if err != nil {
		return result, err
	}
	result.ListenAddress, err = h0_3.Value()
	if err != nil {
		return result, err
	}
	result.PrivateKeyPEM, err = h0_4.Value()
	if err != nil {
		return result, err
	}
	result.PrivateKeyPath, err = h0_5.Value()
	if err != nil {
		return result, err
	}
	result.StaticCerts, err = h0_6.Value()
	if err != nil {
		return result, err
	}
	result.TLS, err = h0_7.Value()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeWebserverPublic struct {
	HTTPSettings autoTypePublicHTTPSettings
}

// DownloadConfigFileName() KV should contain type string
func (autoTypeWebserverPublic) DownloadConfigFileName() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Public/DownloadConfigFileName", codecs.NewJsonCodec[string]())
}

// ExternalAddress() KV should contain type string
func (autoTypeWebserverPublic) ExternalAddress() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Public/ExternalAddress", codecs.NewJsonCodec[string]())
}

type resultWebserverPublic struct {
	HTTPSettings           config.WebserverDetails
	DownloadConfigFileName string
	ExternalAddress        string
}

// Get fetches all fields of resultWebserverPublic in one or more transactions pinned to the same etcd revision.
func (a autoTypeWebserverPublic) Get(ctx context.Context, cli *v3.Client) (result resultWebserverPublic, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.GetTx(txn0.Then(), a.DownloadConfigFileName())
	h0_1 := tetcd.GetTx(txn0.Then(), a.ExternalAddress())
	h0_2 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.CertificatePEM())
	h0_3 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.CertificatePath())
	h0_4 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.Domain())
	h0_5 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.ListenAddress())
	h0_6 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.PrivateKeyPEM())
	h0_7 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.PrivateKeyPath())
	h0_8 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.StaticCerts())
	h0_9 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.TLS())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.DownloadConfigFileName, err = h0_0.Value()
	if err != nil {
		return result, err
	}
	result.ExternalAddress, err = h0_1.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.CertificatePEM, err = h0_2.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.CertificatePath, err = h0_3.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.Domain, err = h0_4.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.ListenAddress, err = h0_5.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.PrivateKeyPEM, err = h0_6.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.PrivateKeyPath, err = h0_7.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.StaticCerts, err = h0_8.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.TLS, err = h0_9.Value()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeTunnelHTTPSettings struct{}

// CertificatePEM() KV should contain type string
func (autoTypeTunnelHTTPSettings) CertificatePEM() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/HTTPSettings/CertificatePEM", codecs.NewJsonCodec[string]())
}

// CertificatePath() KV should contain type string
func (autoTypeTunnelHTTPSettings) CertificatePath() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/HTTPSettings/CertificatePath", codecs.NewJsonCodec[string]())
}

// Domain() KV should contain type string
func (autoTypeTunnelHTTPSettings) Domain() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/HTTPSettings/Domain", codecs.NewJsonCodec[string]())
}

// ListenAddress() KV should contain type string
func (autoTypeTunnelHTTPSettings) ListenAddress() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/HTTPSettings/ListenAddress", codecs.NewJsonCodec[string]())
}

// PrivateKeyPEM() KV should contain type string
func (autoTypeTunnelHTTPSettings) PrivateKeyPEM() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/HTTPSettings/PrivateKeyPEM", codecs.NewJsonCodec[string]())
}

// PrivateKeyPath() KV should contain type string
func (autoTypeTunnelHTTPSettings) PrivateKeyPath() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/HTTPSettings/PrivateKeyPath", codecs.NewJsonCodec[string]())
}

// StaticCerts() KV should contain type bool
func (autoTypeTunnelHTTPSettings) StaticCerts() paths.Path[bool] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/HTTPSettings/StaticCerts", codecs.NewJsonCodec[bool]())
}

// TLS() KV should contain type bool
func (autoTypeTunnelHTTPSettings) TLS() paths.Path[bool] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/HTTPSettings/TLS", codecs.NewJsonCodec[bool]())
}

// Get fetches all fields of WebserverDetails in one or more transactions pinned to the same etcd revision.
func (a autoTypeTunnelHTTPSettings) Get(ctx context.Context, cli *v3.Client) (result config.WebserverDetails, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.GetTx(txn0.Then(), a.CertificatePEM())
	h0_1 := tetcd.GetTx(txn0.Then(), a.CertificatePath())
	h0_2 := tetcd.GetTx(txn0.Then(), a.Domain())
	h0_3 := tetcd.GetTx(txn0.Then(), a.ListenAddress())
	h0_4 := tetcd.GetTx(txn0.Then(), a.PrivateKeyPEM())
	h0_5 := tetcd.GetTx(txn0.Then(), a.PrivateKeyPath())
	h0_6 := tetcd.GetTx(txn0.Then(), a.StaticCerts())
	h0_7 := tetcd.GetTx(txn0.Then(), a.TLS())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.CertificatePEM, err = h0_0.Value()
	if err != nil {
		return result, err
	}
	result.CertificatePath, err = h0_1.Value()
	if err != nil {
		return result, err
	}
	result.Domain, err = h0_2.Value()
	if err != nil {
		return result, err
	}
	result.ListenAddress, err = h0_3.Value()
	if err != nil {
		return result, err
	}
	result.PrivateKeyPEM, err = h0_4.Value()
	if err != nil {
		return result, err
	}
	result.PrivateKeyPath, err = h0_5.Value()
	if err != nil {
		return result, err
	}
	result.StaticCerts, err = h0_6.Value()
	if err != nil {
		return result, err
	}
	result.TLS, err = h0_7.Value()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeTunnelOIDC struct{}

// ClientID() KV should contain type string
func (autoTypeTunnelOIDC) ClientID() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/OIDC/ClientID", codecs.NewJsonCodec[string]())
}

// ClientSecret() KV should contain type string
func (autoTypeTunnelOIDC) ClientSecret() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/OIDC/ClientSecret", codecs.NewJsonCodec[string]())
}

// DeviceUsernameClaim() KV should contain type string
func (autoTypeTunnelOIDC) DeviceUsernameClaim() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/OIDC/DeviceUsernameClaim", codecs.NewJsonCodec[string]())
}

// GroupsClaimName() KV should contain type string
func (autoTypeTunnelOIDC) GroupsClaimName() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/OIDC/GroupsClaimName", codecs.NewJsonCodec[string]())
}

// IssuerURL() KV should contain type string
func (autoTypeTunnelOIDC) IssuerURL() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/OIDC/IssuerURL", codecs.NewJsonCodec[string]())
}

// Scopes() KV should contain type []string
func (autoTypeTunnelOIDC) Scopes() paths.Path[[]string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/OIDC/Scopes", codecs.NewJsonCodec[[]string]())
}

// Get fetches all fields of TunnelOidc in one or more transactions pinned to the same etcd revision.
func (a autoTypeTunnelOIDC) Get(ctx context.Context, cli *v3.Client) (result config.TunnelOidc, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.GetTx(txn0.Then(), a.ClientID())
	h0_1 := tetcd.GetTx(txn0.Then(), a.ClientSecret())
	h0_2 := tetcd.GetTx(txn0.Then(), a.DeviceUsernameClaim())
	h0_3 := tetcd.GetTx(txn0.Then(), a.GroupsClaimName())
	h0_4 := tetcd.GetTx(txn0.Then(), a.IssuerURL())
	h0_5 := tetcd.GetTx(txn0.Then(), a.Scopes())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.ClientID, err = h0_0.Value()
	if err != nil {
		return result, err
	}
	result.ClientSecret, err = h0_1.Value()
	if err != nil {
		return result, err
	}
	result.DeviceUsernameClaim, err = h0_2.Value()
	if err != nil {
		return result, err
	}
	result.GroupsClaimName, err = h0_3.Value()
	if err != nil {
		return result, err
	}
	result.IssuerURL, err = h0_4.Value()
	if err != nil {
		return result, err
	}
	result.Scopes, err = h0_5.Value()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeTunnelPAM struct{}

// ServiceName() KV should contain type string
func (autoTypeTunnelPAM) ServiceName() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/PAM/ServiceName", codecs.NewJsonCodec[string]())
}

// Get fetches all fields of PAM in one or more transactions pinned to the same etcd revision.
func (a autoTypeTunnelPAM) Get(ctx context.Context, cli *v3.Client) (result config.PAM, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.GetTx(txn0.Then(), a.ServiceName())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.ServiceName, err = h0_0.Value()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeWebserverTunnel struct {
	HTTPSettings autoTypeTunnelHTTPSettings
	OIDC         autoTypeTunnelOIDC
	PAM          autoTypeTunnelPAM
}

// DefaultMethod() KV should contain type string
func (autoTypeWebserverTunnel) DefaultMethod() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/DefaultMethod", codecs.NewJsonCodec[string]())
}

// HelpMail() KV should contain type string
func (autoTypeWebserverTunnel) HelpMail() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/HelpMail", codecs.NewJsonCodec[string]())
}

// Issuer() KV should contain type string
func (autoTypeWebserverTunnel) Issuer() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/Issuer", codecs.NewJsonCodec[string]())
}

// MaxSessionLifetimeMinutes() KV should contain type int
func (autoTypeWebserverTunnel) MaxSessionLifetimeMinutes() paths.Path[int] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/MaxSessionLifetimeMinutes", codecs.NewJsonCodec[int]())
}

// Methods() KV should contain type []string
func (autoTypeWebserverTunnel) Methods() paths.Path[[]string] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/Methods", codecs.NewJsonCodec[[]string]())
}

// SessionInactivityTimeoutMinutes() KV should contain type int
func (autoTypeWebserverTunnel) SessionInactivityTimeoutMinutes() paths.Path[int] {
	return paths.NewPath("wag-config/Config/Webserver/Tunnel/SessionInactivityTimeoutMinutes", codecs.NewJsonCodec[int]())
}

type resultWebserverTunnel struct {
	HTTPSettings                    config.WebserverDetails
	HelpMail                        string
	MaxSessionLifetimeMinutes       int
	SessionInactivityTimeoutMinutes int
	DefaultMethod                   string
	Issuer                          string
	Methods                         []string
	OIDC                            config.TunnelOidc
	PAM                             config.PAM
}

// Get fetches all fields of resultWebserverTunnel in one or more transactions pinned to the same etcd revision.
func (a autoTypeWebserverTunnel) Get(ctx context.Context, cli *v3.Client) (result resultWebserverTunnel, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.GetTx(txn0.Then(), a.DefaultMethod())
	h0_1 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.CertificatePEM())
	h0_2 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.CertificatePath())
	h0_3 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.Domain())
	h0_4 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.ListenAddress())
	h0_5 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.PrivateKeyPEM())
	h0_6 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.PrivateKeyPath())
	h0_7 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.StaticCerts())
	h0_8 := tetcd.GetTx(txn0.Then(), a.HTTPSettings.TLS())
	h0_9 := tetcd.GetTx(txn0.Then(), a.HelpMail())
	h0_10 := tetcd.GetTx(txn0.Then(), a.Issuer())
	h0_11 := tetcd.GetTx(txn0.Then(), a.MaxSessionLifetimeMinutes())
	h0_12 := tetcd.GetTx(txn0.Then(), a.Methods())
	h0_13 := tetcd.GetTx(txn0.Then(), a.OIDC.ClientID())
	h0_14 := tetcd.GetTx(txn0.Then(), a.OIDC.ClientSecret())
	h0_15 := tetcd.GetTx(txn0.Then(), a.OIDC.DeviceUsernameClaim())
	h0_16 := tetcd.GetTx(txn0.Then(), a.OIDC.GroupsClaimName())
	h0_17 := tetcd.GetTx(txn0.Then(), a.OIDC.IssuerURL())
	h0_18 := tetcd.GetTx(txn0.Then(), a.OIDC.Scopes())
	h0_19 := tetcd.GetTx(txn0.Then(), a.PAM.ServiceName())
	h0_20 := tetcd.GetTx(txn0.Then(), a.SessionInactivityTimeoutMinutes())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.DefaultMethod, err = h0_0.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.CertificatePEM, err = h0_1.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.CertificatePath, err = h0_2.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.Domain, err = h0_3.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.ListenAddress, err = h0_4.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.PrivateKeyPEM, err = h0_5.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.PrivateKeyPath, err = h0_6.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.StaticCerts, err = h0_7.Value()
	if err != nil {
		return result, err
	}
	result.HTTPSettings.TLS, err = h0_8.Value()
	if err != nil {
		return result, err
	}
	result.HelpMail, err = h0_9.Value()
	if err != nil {
		return result, err
	}
	result.Issuer, err = h0_10.Value()
	if err != nil {
		return result, err
	}
	result.MaxSessionLifetimeMinutes, err = h0_11.Value()
	if err != nil {
		return result, err
	}
	result.Methods, err = h0_12.Value()
	if err != nil {
		return result, err
	}
	result.OIDC.ClientID, err = h0_13.Value()
	if err != nil {
		return result, err
	}
	result.OIDC.ClientSecret, err = h0_14.Value()
	if err != nil {
		return result, err
	}
	result.OIDC.DeviceUsernameClaim, err = h0_15.Value()
	if err != nil {
		return result, err
	}
	result.OIDC.GroupsClaimName, err = h0_16.Value()
	if err != nil {
		return result, err
	}
	result.OIDC.IssuerURL, err = h0_17.Value()
	if err != nil {
		return result, err
	}
	result.OIDC.Scopes, err = h0_18.Value()
	if err != nil {
		return result, err
	}
	result.PAM.ServiceName, err = h0_19.Value()
	if err != nil {
		return result, err
	}
	result.SessionInactivityTimeoutMinutes, err = h0_20.Value()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeConfigWebserver struct {
	Acme       autoTypeWebserverAcme
	Management autoTypeWebserverManagement
	Public     autoTypeWebserverPublic
	Tunnel     autoTypeWebserverTunnel
}

// Lockout() KV should contain type int
func (autoTypeConfigWebserver) Lockout() paths.Path[int] {
	return paths.NewPath("wag-config/Config/Webserver/Lockout", codecs.NewJsonCodec[int]())
}

type resultConfigWebserver struct {
	Acme struct {
		Email              string
		CAProvider         string
		CloudflareDNSToken string
	}
	Public struct {
		HTTPSettings           config.WebserverDetails
		DownloadConfigFileName string
		ExternalAddress        string
	}
	Lockout int
	Tunnel  struct {
		HTTPSettings                    config.WebserverDetails
		HelpMail                        string
		MaxSessionLifetimeMinutes       int
		SessionInactivityTimeoutMinutes int
		DefaultMethod                   string
		Issuer                          string
		Methods                         []string
		OIDC                            config.TunnelOidc
		PAM                             config.PAM
	}
	Management struct {
		HTTPSettings config.WebserverDetails
		Enabled      bool
		Password     struct {
			Enabled *bool
		}
		OIDC struct {
			IssuerURL    string
			ClientSecret string
			ClientID     string
			Enabled      bool
		}
	}
}

// Get fetches all fields of resultConfigWebserver in one or more transactions pinned to the same etcd revision.
func (a autoTypeConfigWebserver) Get(ctx context.Context, cli *v3.Client) (result resultConfigWebserver, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.GetTx(txn0.Then(), a.Acme.CAProvider())
	h0_1 := tetcd.GetTx(txn0.Then(), a.Acme.CloudflareDNSToken())
	h0_2 := tetcd.GetTx(txn0.Then(), a.Acme.Email())
	h0_3 := tetcd.GetTx(txn0.Then(), a.Lockout())
	h0_4 := tetcd.GetTx(txn0.Then(), a.Management.Enabled())
	h0_5 := tetcd.GetTx(txn0.Then(), a.Management.HTTPSettings.CertificatePEM())
	h0_6 := tetcd.GetTx(txn0.Then(), a.Management.HTTPSettings.CertificatePath())
	h0_7 := tetcd.GetTx(txn0.Then(), a.Management.HTTPSettings.Domain())
	h0_8 := tetcd.GetTx(txn0.Then(), a.Management.HTTPSettings.ListenAddress())
	h0_9 := tetcd.GetTx(txn0.Then(), a.Management.HTTPSettings.PrivateKeyPEM())
	h0_10 := tetcd.GetTx(txn0.Then(), a.Management.HTTPSettings.PrivateKeyPath())
	h0_11 := tetcd.GetTx(txn0.Then(), a.Management.HTTPSettings.StaticCerts())
	h0_12 := tetcd.GetTx(txn0.Then(), a.Management.HTTPSettings.TLS())
	h0_13 := tetcd.GetTx(txn0.Then(), a.Management.OIDC.ClientID())
	h0_14 := tetcd.GetTx(txn0.Then(), a.Management.OIDC.ClientSecret())
	h0_15 := tetcd.GetTx(txn0.Then(), a.Management.OIDC.Enabled())
	h0_16 := tetcd.GetTx(txn0.Then(), a.Management.OIDC.IssuerURL())
	h0_17 := tetcd.GetTx(txn0.Then(), a.Management.Password.Enabled())
	h0_18 := tetcd.GetTx(txn0.Then(), a.Public.DownloadConfigFileName())
	h0_19 := tetcd.GetTx(txn0.Then(), a.Public.ExternalAddress())
	h0_20 := tetcd.GetTx(txn0.Then(), a.Public.HTTPSettings.CertificatePEM())
	h0_21 := tetcd.GetTx(txn0.Then(), a.Public.HTTPSettings.CertificatePath())
	h0_22 := tetcd.GetTx(txn0.Then(), a.Public.HTTPSettings.Domain())
	h0_23 := tetcd.GetTx(txn0.Then(), a.Public.HTTPSettings.ListenAddress())
	h0_24 := tetcd.GetTx(txn0.Then(), a.Public.HTTPSettings.PrivateKeyPEM())
	h0_25 := tetcd.GetTx(txn0.Then(), a.Public.HTTPSettings.PrivateKeyPath())
	h0_26 := tetcd.GetTx(txn0.Then(), a.Public.HTTPSettings.StaticCerts())
	h0_27 := tetcd.GetTx(txn0.Then(), a.Public.HTTPSettings.TLS())
	h0_28 := tetcd.GetTx(txn0.Then(), a.Tunnel.DefaultMethod())
	h0_29 := tetcd.GetTx(txn0.Then(), a.Tunnel.HTTPSettings.CertificatePEM())
	h0_30 := tetcd.GetTx(txn0.Then(), a.Tunnel.HTTPSettings.CertificatePath())
	h0_31 := tetcd.GetTx(txn0.Then(), a.Tunnel.HTTPSettings.Domain())
	h0_32 := tetcd.GetTx(txn0.Then(), a.Tunnel.HTTPSettings.ListenAddress())
	h0_33 := tetcd.GetTx(txn0.Then(), a.Tunnel.HTTPSettings.PrivateKeyPEM())
	h0_34 := tetcd.GetTx(txn0.Then(), a.Tunnel.HTTPSettings.PrivateKeyPath())
	h0_35 := tetcd.GetTx(txn0.Then(), a.Tunnel.HTTPSettings.StaticCerts())
	h0_36 := tetcd.GetTx(txn0.Then(), a.Tunnel.HTTPSettings.TLS())
	h0_37 := tetcd.GetTx(txn0.Then(), a.Tunnel.HelpMail())
	h0_38 := tetcd.GetTx(txn0.Then(), a.Tunnel.Issuer())
	h0_39 := tetcd.GetTx(txn0.Then(), a.Tunnel.MaxSessionLifetimeMinutes())
	h0_40 := tetcd.GetTx(txn0.Then(), a.Tunnel.Methods())
	h0_41 := tetcd.GetTx(txn0.Then(), a.Tunnel.OIDC.ClientID())
	h0_42 := tetcd.GetTx(txn0.Then(), a.Tunnel.OIDC.ClientSecret())
	h0_43 := tetcd.GetTx(txn0.Then(), a.Tunnel.OIDC.DeviceUsernameClaim())
	h0_44 := tetcd.GetTx(txn0.Then(), a.Tunnel.OIDC.GroupsClaimName())
	h0_45 := tetcd.GetTx(txn0.Then(), a.Tunnel.OIDC.IssuerURL())
	h0_46 := tetcd.GetTx(txn0.Then(), a.Tunnel.OIDC.Scopes())
	h0_47 := tetcd.GetTx(txn0.Then(), a.Tunnel.PAM.ServiceName())
	h0_48 := tetcd.GetTx(txn0.Then(), a.Tunnel.SessionInactivityTimeoutMinutes())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Acme.CAProvider, err = h0_0.Value()
	if err != nil {
		return result, err
	}
	result.Acme.CloudflareDNSToken, err = h0_1.Value()
	if err != nil {
		return result, err
	}
	result.Acme.Email, err = h0_2.Value()
	if err != nil {
		return result, err
	}
	result.Lockout, err = h0_3.Value()
	if err != nil {
		return result, err
	}
	result.Management.Enabled, err = h0_4.Value()
	if err != nil {
		return result, err
	}
	result.Management.HTTPSettings.CertificatePEM, err = h0_5.Value()
	if err != nil {
		return result, err
	}
	result.Management.HTTPSettings.CertificatePath, err = h0_6.Value()
	if err != nil {
		return result, err
	}
	result.Management.HTTPSettings.Domain, err = h0_7.Value()
	if err != nil {
		return result, err
	}
	result.Management.HTTPSettings.ListenAddress, err = h0_8.Value()
	if err != nil {
		return result, err
	}
	result.Management.HTTPSettings.PrivateKeyPEM, err = h0_9.Value()
	if err != nil {
		return result, err
	}
	result.Management.HTTPSettings.PrivateKeyPath, err = h0_10.Value()
	if err != nil {
		return result, err
	}
	result.Management.HTTPSettings.StaticCerts, err = h0_11.Value()
	if err != nil {
		return result, err
	}
	result.Management.HTTPSettings.TLS, err = h0_12.Value()
	if err != nil {
		return result, err
	}
	result.Management.OIDC.ClientID, err = h0_13.Value()
	if err != nil {
		return result, err
	}
	result.Management.OIDC.ClientSecret, err = h0_14.Value()
	if err != nil {
		return result, err
	}
	result.Management.OIDC.Enabled, err = h0_15.Value()
	if err != nil {
		return result, err
	}
	result.Management.OIDC.IssuerURL, err = h0_16.Value()
	if err != nil {
		return result, err
	}
	result.Management.Password.Enabled, err = h0_17.Value()
	if err != nil {
		return result, err
	}
	result.Public.DownloadConfigFileName, err = h0_18.Value()
	if err != nil {
		return result, err
	}
	result.Public.ExternalAddress, err = h0_19.Value()
	if err != nil {
		return result, err
	}
	result.Public.HTTPSettings.CertificatePEM, err = h0_20.Value()
	if err != nil {
		return result, err
	}
	result.Public.HTTPSettings.CertificatePath, err = h0_21.Value()
	if err != nil {
		return result, err
	}
	result.Public.HTTPSettings.Domain, err = h0_22.Value()
	if err != nil {
		return result, err
	}
	result.Public.HTTPSettings.ListenAddress, err = h0_23.Value()
	if err != nil {
		return result, err
	}
	result.Public.HTTPSettings.PrivateKeyPEM, err = h0_24.Value()
	if err != nil {
		return result, err
	}
	result.Public.HTTPSettings.PrivateKeyPath, err = h0_25.Value()
	if err != nil {
		return result, err
	}
	result.Public.HTTPSettings.StaticCerts, err = h0_26.Value()
	if err != nil {
		return result, err
	}
	result.Public.HTTPSettings.TLS, err = h0_27.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.DefaultMethod, err = h0_28.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.HTTPSettings.CertificatePEM, err = h0_29.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.HTTPSettings.CertificatePath, err = h0_30.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.HTTPSettings.Domain, err = h0_31.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.HTTPSettings.ListenAddress, err = h0_32.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.HTTPSettings.PrivateKeyPEM, err = h0_33.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.HTTPSettings.PrivateKeyPath, err = h0_34.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.HTTPSettings.StaticCerts, err = h0_35.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.HTTPSettings.TLS, err = h0_36.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.HelpMail, err = h0_37.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.Issuer, err = h0_38.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.MaxSessionLifetimeMinutes, err = h0_39.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.Methods, err = h0_40.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.OIDC.ClientID, err = h0_41.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.OIDC.ClientSecret, err = h0_42.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.OIDC.DeviceUsernameClaim, err = h0_43.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.OIDC.GroupsClaimName, err = h0_44.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.OIDC.IssuerURL, err = h0_45.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.OIDC.Scopes, err = h0_46.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.PAM.ServiceName, err = h0_47.Value()
	if err != nil {
		return result, err
	}
	result.Tunnel.SessionInactivityTimeoutMinutes, err = h0_48.Value()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeConfigWireguard struct{}

// Address() KV should contain type string
func (autoTypeConfigWireguard) Address() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Wireguard/Address", codecs.NewJsonCodec[string]())
}

// DNS() KV should contain type []string
func (autoTypeConfigWireguard) DNS() paths.Path[[]string] {
	return paths.NewPath("wag-config/Config/Wireguard/DNS", codecs.NewJsonCodec[[]string]())
}

// DevName() KV should contain type string
func (autoTypeConfigWireguard) DevName() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Wireguard/DevName", codecs.NewJsonCodec[string]())
}

// ListenPort() KV should contain type int
func (autoTypeConfigWireguard) ListenPort() paths.Path[int] {
	return paths.NewPath("wag-config/Config/Wireguard/ListenPort", codecs.NewJsonCodec[int]())
}

// LogLevel() KV should contain type int
func (autoTypeConfigWireguard) LogLevel() paths.Path[int] {
	return paths.NewPath("wag-config/Config/Wireguard/LogLevel", codecs.NewJsonCodec[int]())
}

// MTU() KV should contain type int
func (autoTypeConfigWireguard) MTU() paths.Path[int] {
	return paths.NewPath("wag-config/Config/Wireguard/MTU", codecs.NewJsonCodec[int]())
}

// PrivateKey() KV should contain type string
func (autoTypeConfigWireguard) PrivateKey() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Wireguard/PrivateKey", codecs.NewJsonCodec[string]())
}

// ServerPersistentKeepAlive() KV should contain type int
func (autoTypeConfigWireguard) ServerPersistentKeepAlive() paths.Path[int] {
	return paths.NewPath("wag-config/Config/Wireguard/ServerPersistentKeepAlive", codecs.NewJsonCodec[int]())
}

type resultConfigWireguard struct {
	DevName                   string
	ListenPort                int
	PrivateKey                string
	Address                   string
	MTU                       int
	LogLevel                  int
	Range                     *net.IPNet
	ServerAddress             net.IP
	ServerPersistentKeepAlive int
	DNS                       []string
}

// Get fetches all fields of resultConfigWireguard in one or more transactions pinned to the same etcd revision.
func (a autoTypeConfigWireguard) Get(ctx context.Context, cli *v3.Client) (result resultConfigWireguard, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.GetTx(txn0.Then(), a.Address())
	h0_1 := tetcd.GetTx(txn0.Then(), a.DNS())
	h0_2 := tetcd.GetTx(txn0.Then(), a.DevName())
	h0_3 := tetcd.GetTx(txn0.Then(), a.ListenPort())
	h0_4 := tetcd.GetTx(txn0.Then(), a.LogLevel())
	h0_5 := tetcd.GetTx(txn0.Then(), a.MTU())
	h0_6 := tetcd.GetTx(txn0.Then(), a.PrivateKey())
	h0_7 := tetcd.GetTx(txn0.Then(), a.ServerPersistentKeepAlive())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Address, err = h0_0.Value()
	if err != nil {
		return result, err
	}
	result.DNS, err = h0_1.Value()
	if err != nil {
		return result, err
	}
	result.DevName, err = h0_2.Value()
	if err != nil {
		return result, err
	}
	result.ListenPort, err = h0_3.Value()
	if err != nil {
		return result, err
	}
	result.LogLevel, err = h0_4.Value()
	if err != nil {
		return result, err
	}
	result.MTU, err = h0_5.Value()
	if err != nil {
		return result, err
	}
	result.PrivateKey, err = h0_6.Value()
	if err != nil {
		return result, err
	}
	result.ServerPersistentKeepAlive, err = h0_7.Value()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeConfig struct {
	Acls      autoTypeConfigAcls
	Webserver autoTypeConfigWebserver
	Wireguard autoTypeConfigWireguard
}

// CheckUpdates() KV should contain type bool
func (autoTypeConfig) CheckUpdates() paths.Path[bool] {
	return paths.NewPath("wag-config/Config/CheckUpdates", codecs.NewJsonCodec[bool]())
}

// DevMode() KV should contain type bool
func (autoTypeConfig) DevMode() paths.Path[bool] {
	return paths.NewPath("wag-config/Config/DevMode", codecs.NewJsonCodec[bool]())
}

// ExposePorts() KV should contain type []string
func (autoTypeConfig) ExposePorts() paths.Path[[]string] {
	return paths.NewPath("wag-config/Config/ExposePorts", codecs.NewJsonCodec[[]string]())
}

// GID() KV should contain type *int
func (autoTypeConfig) GID() paths.Path[*int] {
	return paths.NewPath("wag-config/Config/GID", codecs.NewJsonCodec[*int]())
}

// NAT() KV should contain type *bool
func (autoTypeConfig) NAT() paths.Path[*bool] {
	return paths.NewPath("wag-config/Config/NAT", codecs.NewJsonCodec[*bool]())
}

// NATExcludeRanges() KV should contain type []string
func (autoTypeConfig) NATExcludeRanges() paths.Path[[]string] {
	return paths.NewPath("wag-config/Config/NATExcludeRanges", codecs.NewJsonCodec[[]string]())
}

// NumberProxies() KV should contain type int
func (autoTypeConfig) NumberProxies() paths.Path[int] {
	return paths.NewPath("wag-config/Config/NumberProxies", codecs.NewJsonCodec[int]())
}

// Socket() KV should contain type string
func (autoTypeConfig) Socket() paths.Path[string] {
	return paths.NewPath("wag-config/Config/Socket", codecs.NewJsonCodec[string]())
}

var Config = autoTypeConfig{}
