// Code generated by https://github.com/NHAS/tetcd, DO NOT EDIT.
package data

import (
	"context"
	tetcd "github.com/NHAS/tetcd"
	codecs "github.com/NHAS/tetcd/codecs"
	paths "github.com/NHAS/tetcd/paths"
	config "github.com/NHAS/wag/internal/config"
	control "github.com/NHAS/wag/pkg/control"
	v3 "go.etcd.io/etcd/client/v3"
)

type autoTypeDevicesDHCP struct{}

// Abandoned() is a map path with prefix wag-config-internal/InternalConfig/Devices/DHCP/Abandoned, value type string
func (autoTypeDevicesDHCP) Abandoned() paths.MapPath[string] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Devices/DHCP/Abandoned", codecs.NewJsonCodec[string](), false)
}

// End() KV should contain type string
func (autoTypeDevicesDHCP) End() paths.Path[string] {
	return paths.NewPath("wag-config-internal/InternalConfig/Devices/DHCP/End", codecs.NewJsonCodec[string]())
}

// Locks() KV should contain type string
func (autoTypeDevicesDHCP) Locks() paths.Path[string] {
	return paths.NewPath("wag-config-internal/InternalConfig/Devices/DHCP/Locks", codecs.NewJsonCodec[string]())
}

// Get fetches all fields of DHCP in one or more transactions pinned to the same etcd revision.
func (a autoTypeDevicesDHCP) Get(ctx context.Context, cli *v3.Client) (result config.DHCP, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.ListTx(txn0.Then(), a.Abandoned())
	h0_1 := tetcd.GetTx(txn0.Then(), a.End())
	h0_2 := tetcd.GetTx(txn0.Then(), a.Locks())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Abandoned, err = h0_0.Entries()
	if err != nil {
		return result, err
	}
	result.End, err = h0_1.Value()
	if err != nil {
		return result, err
	}
	result.Locks, err = h0_2.Value()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeInternalConfigDevices struct {
	DHCP autoTypeDevicesDHCP
}

// Challenges() is a slice map path with prefix wag-config-internal/InternalConfig/Devices/Challenges, value type github.com/NHAS/wag/internal/config.DeviceChallenge
func (autoTypeInternalConfigDevices) Challenges() paths.MapSlicePath[config.DeviceChallenge] {
	return paths.NewMapSlicePath("wag-config-internal/InternalConfig/Devices/Challenges", codecs.NewJsonCodec[config.DeviceChallenge](), false)
}

// Machines() is a slice map path with prefix wag-config-internal/InternalConfig/Devices/Machines, value type github.com/NHAS/wag/internal/config.Device
func (autoTypeInternalConfigDevices) Machines() paths.MapSlicePath[config.Device] {
	return paths.NewMapSlicePath("wag-config-internal/InternalConfig/Devices/Machines", codecs.NewJsonCodec[config.Device](), false)
}

// Sessions() is a map path with prefix wag-config-internal/InternalConfig/Devices/Sessions, value type github.com/NHAS/wag/internal/config.DeviceSession
func (autoTypeInternalConfigDevices) Sessions() paths.MapPath[config.DeviceSession] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Devices/Sessions", codecs.NewJsonCodec[config.DeviceSession](), false)
}

// Get fetches all fields of Devices in one or more transactions pinned to the same etcd revision.
func (a autoTypeInternalConfigDevices) Get(ctx context.Context, cli *v3.Client) (result config.Devices, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.DynamicCollectionTx(txn0.Then(), a.Challenges())
	h0_1 := tetcd.ListTx(txn0.Then(), a.DHCP.Abandoned())
	h0_2 := tetcd.GetTx(txn0.Then(), a.DHCP.End())
	h0_3 := tetcd.GetTx(txn0.Then(), a.DHCP.Locks())
	h0_4 := tetcd.DynamicCollectionTx(txn0.Then(), a.Machines())
	h0_5 := tetcd.ListTx(txn0.Then(), a.Sessions())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Challenges, err = h0_0.Entries()
	if err != nil {
		return result, err
	}
	result.DHCP.Abandoned, err = h0_1.Entries()
	if err != nil {
		return result, err
	}
	result.DHCP.End, err = h0_2.Value()
	if err != nil {
		return result, err
	}
	result.DHCP.Locks, err = h0_3.Value()
	if err != nil {
		return result, err
	}
	result.Machines, err = h0_4.Entries()
	if err != nil {
		return result, err
	}
	result.Sessions, err = h0_5.Entries()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeInternalConfigIndexes struct{}

// Groups() is a map path with prefix wag-config-internal/InternalConfig/Indexes/Groups, value type github.com/NHAS/wag/internal/config.GroupInfo
func (autoTypeInternalConfigIndexes) Groups() paths.MapPath[config.GroupInfo] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Indexes/Groups", codecs.NewJsonCodec[config.GroupInfo](), false)
}

// UserMembership() is a slice map path with prefix wag-config-internal/InternalConfig/Indexes/UserMembership, value type github.com/NHAS/wag/internal/config.MembershipInfo
func (autoTypeInternalConfigIndexes) UserMembership() paths.MapSlicePath[config.MembershipInfo] {
	return paths.NewMapSlicePath("wag-config-internal/InternalConfig/Indexes/UserMembership", codecs.NewJsonCodec[config.MembershipInfo](), false)
}

// Get fetches all fields of Indexes in one or more transactions pinned to the same etcd revision.
func (a autoTypeInternalConfigIndexes) Get(ctx context.Context, cli *v3.Client) (result config.Indexes, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.ListTx(txn0.Then(), a.Groups())
	h0_1 := tetcd.DynamicCollectionTx(txn0.Then(), a.UserMembership())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Groups, err = h0_0.Entries()
	if err != nil {
		return result, err
	}
	result.UserMembership, err = h0_1.Entries()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeReferencesDevices struct{}

// Address() is a map path with prefix wag-config-internal/InternalConfig/References/Devices/Address, value type github.com/NHAS/wag/internal/config.DeviceRef
func (autoTypeReferencesDevices) Address() paths.MapPath[config.DeviceRef] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/References/Devices/Address", codecs.NewJsonCodec[config.DeviceRef](), false)
}

// PublicKey() is a map path with prefix wag-config-internal/InternalConfig/References/Devices/PublicKey, value type github.com/NHAS/wag/internal/config.DeviceRef
func (autoTypeReferencesDevices) PublicKey() paths.MapPath[config.DeviceRef] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/References/Devices/PublicKey", codecs.NewJsonCodec[config.DeviceRef](), false)
}

// Tag() is a map path with prefix wag-config-internal/InternalConfig/References/Devices/Tag, value type github.com/NHAS/wag/internal/config.DeviceRef
func (autoTypeReferencesDevices) Tag() paths.MapPath[config.DeviceRef] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/References/Devices/Tag", codecs.NewJsonCodec[config.DeviceRef](), false)
}

// Get fetches all fields of DevicesReferences in one or more transactions pinned to the same etcd revision.
func (a autoTypeReferencesDevices) Get(ctx context.Context, cli *v3.Client) (result config.DevicesReferences, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.ListTx(txn0.Then(), a.Address())
	h0_1 := tetcd.ListTx(txn0.Then(), a.PublicKey())
	h0_2 := tetcd.ListTx(txn0.Then(), a.Tag())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Address, err = h0_0.Entries()
	if err != nil {
		return result, err
	}
	result.PublicKey, err = h0_1.Entries()
	if err != nil {
		return result, err
	}
	result.Tag, err = h0_2.Entries()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeInternalConfigReferences struct {
	Devices autoTypeReferencesDevices
}

// Get fetches all fields of References in one or more transactions pinned to the same etcd revision.
func (a autoTypeInternalConfigReferences) Get(ctx context.Context, cli *v3.Client) (result config.References, err error) {
	txn0 := tetcd.NewTxn(ctx, cli)
	h0_0 := tetcd.ListTx(txn0.Then(), a.Devices.Address())
	h0_1 := tetcd.ListTx(txn0.Then(), a.Devices.PublicKey())
	h0_2 := tetcd.ListTx(txn0.Then(), a.Devices.Tag())
	if err := txn0.Commit(); err != nil {
		return result, err
	}
	result.Devices.Address, err = h0_0.Entries()
	if err != nil {
		return result, err
	}
	result.Devices.PublicKey, err = h0_1.Entries()
	if err != nil {
		return result, err
	}
	result.Devices.Tag, err = h0_2.Entries()
	if err != nil {
		return result, err
	}
	return result, nil
}

type autoTypeInternalConfig struct {
	Devices    autoTypeInternalConfigDevices
	Indexes    autoTypeInternalConfigIndexes
	References autoTypeInternalConfigReferences
}

// RegistrationTokens() is a map path with prefix wag-config-internal/InternalConfig/RegistrationTokens, value type github.com/NHAS/wag/pkg/control.RegistrationResult
func (autoTypeInternalConfig) RegistrationTokens() paths.MapPath[control.RegistrationResult] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/RegistrationTokens", codecs.NewJsonCodec[control.RegistrationResult](), false)
}

// Users() is a map path with prefix wag-config-internal/InternalConfig/Users, value type github.com/NHAS/wag/internal/config.UserModel
func (autoTypeInternalConfig) Users() paths.MapPath[config.UserModel] {
	return paths.NewMapPath("wag-config-internal/InternalConfig/Users", codecs.NewJsonCodec[config.UserModel](), false)
}

var InternalConfig = autoTypeInternalConfig{}
